### ISSUE TITLE
Add preferences dialog to top menu

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytripgui#103]
Here static configuration could be stored:
- remote or local TRiP execution
- server name for remote execution
- working dir
- TRiPPATH to various base data
- login (evt. inc. encrypted password? Passwordless login via ssh keys is possible)

These should be persistent, i.e. be stored in some local dir.

**Comment by grzanka** [comment]
Users running Linux can simple work with keys. In this scenario not much has to be done - its enough to ask user to put public cert on the remote machine.

For Windoze users its more problematic. Saving password (even encrypted) in a config file its not safe. What about generating private+public key in a pytripgui and ask user to move public key by himself to the server. Then store somewhere private key and ask user to type passphrase on first run of GUI ?

**Comment by nbassler** [comment]
tripexecuter works fine with password-less login (i.e. keys were exchanged) this was tested before.

I dont think we should waste too much time on it. I think a text box saying that we recommend ssh keyexchange, and simply tell them that any passwords entered in that text field will be stored unencrypted and is thus readable by anyone.
