### ISSUE TITLE
STDERR not redirected to TripLog dialog

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytripgui#104]
When trying to execute TRiP, only the first welcome line is forwarded to the TripLog dialog.

It seems that most part of STDOUT and all of STDERR is missing.

Could be a pytrip issue.

**Comment by grzanka** [comment]
See https://github.com/pytrip/pytrip/pull/289/files - it may be a source of problems

**Comment by nbassler** [comment]
TripLog is currently absent. Need a new solution for this.
