### ISSUE TITLE
New plan with ROIs fails

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#121]
I've started with opening Voxelplan patient, then right-clicked on "Plans" and then "New plan with ROIs".

![image](https://cloud.githubusercontent.com/assets/7374733/25610039/efe14ce4-2f21-11e7-812b-18e52ca9d1be.png)

![image](https://cloud.githubusercontent.com/assets/7374733/25610058/ffde8c92-2f21-11e7-88b5-2de0d91c60b9.png)

**Comment by nbassler** [comment]
This should be resolved with the new API #123 
Works for me since #123
