### ISSUE TITLE
Consider loading directly UI files

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#205]
See https://doc.qt.io/qtforpython/tutorials/basictutorial/uifiles.html, it mentiones QtUiTools class to load directly (dynamically) UI files.

In such way `makeui.sh` script (which calls `pyuic5`) could be dropped.

**Comment by ljelen** [comment]
To me this is a way better method, because now after each checkout I have to make makeiu.sh to make sure everything is up to date

**Comment by grzanka** [comment]
So please implement it :)

**Comment by ljelen** [comment]
It requires QtUiTools from PySide2, and I've got some problems with installing it.

**Comment by grzanka** [comment]
What about using `uic` method, as described here https://nitratine.net/blog/post/how-to-import-a-pyqt5-ui-file-in-a-python-gui/ ?
