### ISSUE TITLE
Pickle dont save files at exit

### ISSUE THREAD

**Issue by ljelen** [pytrip/pytripgui#215]
Pickle only saves files, when you click save in settings->beam kernels. So if you want to save data from settings->Trip98 config with pickle you need to navigate  to beam kernels and then just click save.

**Comment by grzanka** [comment]
Why don't we save pickle on application exit ?

**Comment by nbassler** [comment]
I think settings should be saved the latest when leaving the settings window.

(Also: I noticed that modern GUIs save/store/employ the data immediatly when you change a value.)
