### ISSUE TITLE
Plan execution on DICOM results in app crash

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#232]
```
raceback (most recent call last):
  File "/home/grzanka/PycharmProjects/pytripgui/pytripgui/controller/tree_menu_cont.py", line 120, in execute_plan
    logger.debug("Temporary dir:{}".format(self.model.wdir))
AttributeError: 'MainModel' object has no attribute 'wdir'
[1]    13531 abort (core dumped)  PYTHONPATH=.:../pytrip python pytripgui/main.py
```

Trying to make a plan on `aria-phantom-contours-branching` DICOM

**Comment by grzanka** [comment]
DICOM itself loads nicely:
![image](https://user-images.githubusercontent.com/7374733/64170382-48776300-ce50-11e9-8574-cc94014e010e.png)

**Comment by Yoanka** [comment]
Issue looks deprecated - referenced code no longer exists and the feature should work correctly.

**Comment by grzanka** [comment]
I tested it again on `aria-phantom-contours-branching` and it works well
