### ISSUE TITLE
Reimplement regresed functions:

### ISSUE THREAD

**Issue by ljelen** [pytrip/pytripgui#240]
Reimplement regresed functions:
- [x] Display structure of data in tree view
- [x] display DOS | LET | CTX after plan execution
- [x] Make plan
- [x] roll back scroll instead of over scroll
- [x] display current slice position
- [x] make main window view-controller
- [x] fix pytripgui version in 'about'
- [x] add some info to guide user
- [x] execute plan

**Comment by grzanka** [comment]
Are some of the functions already implemented ? Please make a PR "in progress" to see how is it going
