### ISSUE TITLE
Pytrip dependency should be fixed to working version

### ISSUE THREAD

**Issue by ljelen** [pytrip/pytripgui#254]
Dependency package 'Pytrip98' should be fixed to a concrete working version

**Comment by grzanka** [comment]
why not a range or a minimum version ?

**Comment by ljelen** [comment]
Range is ok, but a minimum version not.
When we will make some changes in pytrip API, then pytripgui will automatically gets newest pytrip API which means errors. 
If someone in the future will want to bump up pytrip version number, he should make sure that pytripgui uses pytrip API in right way.

**Comment by grzanka** [comment]
If we assume that we work with semantic versioning then it should be enough if we use a range of pytrip versions between 2.6 and 3.0.

**Comment by grzanka** [comment]
When making changes to the trip98 API we should bump MAJOR number versions. Moreover we have weekly cron jobs which should test for such type of errors.

The same applies to numpy - do you think it makes sense to have an upper limit on numpy requirement ?

Take a look on how scipy is treating numpy dependency: https://github.com/scipy/scipy/blob/master/setup.py#L459
They assume to rely on 1.5 year old numpy .

**Comment by ljelen** [comment]
To me range witch classic approach that major number means changes in public API is ok.
