### ISSUE TITLE
Add windows wheel package

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#26]

**Comment by grzanka** [comment]
First part in https://github.com/pytrip/pytripgui/pull/29

**Comment by nbassler** [comment]
@grzanka will this still be needed with your fancy new installer?

**Comment by grzanka** [comment]
@nbassler In my opinion it is needed. Windows installer is huge (~100MB) and update is problematic (uninstall old version, download new installer, install new version). Moreover windows installer comes together with fixed pytrip (core, not gui) version.
With pip you can keep same version of GUI and update only core part.
For advanced Windows users its better to have pip.

**Comment by nbassler** [comment]
removed priority, since there is a *setup.exe available now

**Comment by grzanka** [comment]
In fact Windows wheel package exists, see https://pypi.python.org/pypi/pytrip98gui/
We have i.e. `pytrip98gui-0.3.1-py2-none-any.whl` which is OS-independent but require pytrip98 installation. This one has Windows-specific binary wheels which require scipy.
Scipy installation under Windows may be major obstacle for average user, as it require to avoid installing python from https://www.python.org/downloads/ but to fetch Anaconda package (~500MB) and install scipy not using `pip install ...` but using `conda install ...`

I'd say this issue may be closed, but a better documentation is needed.
