### ISSUE TITLE
No atribute  error

### ISSUE THREAD

**Issue by ljelen** [pytrip/pytripgui#274]
After successfully installation of pytripgui on [windows, python 3.6] error occurs if I try to run the app:

> C:\Users\JelenL\AppData\Local\Continuum\anaconda3\envs\pytripgui\python.exe C:/Users/JelenL/PycharmProjects/pytripgui/pytripgui/main.py
> Traceback (most recent call last):
>   File "C:/Users/JelenL/PycharmProjects/pytripgui/pytripgui/main.py", line 7, in <module>
>     from pytripgui.main_window_qt_vc.main_window_view import MainWindowQtView
>   File "C:\Users\JelenL\PycharmProjects\pytripgui\pytripgui\__init__.py", line 7, in <module>
>     spec = importlib.util.find_spec('pytripgui')
> AttributeError: module 'importlib' has no attribute 'util'

Related topic:
https://stackoverflow.com/questions/39660934/error-when-using-importlib-util-to-check-for-library/39661116

it works when I change 
> import importlib
> spec = importlib.util.find_spec('pytripgui')

to

> from importlib import util
> spec = util.find_spec('pytripgui')

in __init__.py file in the main directory

**Comment by grzanka** [comment]
Please give more details how to reproduce, in my case it works (Python3.6, Anaconda on Windows):

![image](https://user-images.githubusercontent.com/7374733/75184386-98bae800-5744-11ea-9501-407247baf893.png)
![image](https://user-images.githubusercontent.com/7374733/75184462-b2f4c600-5744-11ea-8475-98c4bc56f049.png)

**Comment by grzanka** [comment]
What do you mean by:

> After successfully installation of pytripgui 

? Was it installation via pip ?

**Comment by ljelen** [comment]
> What do you mean by:
> 
> > After successfully installation of pytripgui
> 
> ? Was it installation via pip ?

I installed Anaconda, then create a new clean environment. Next, install pytrip from sources: git master, then installed pytrip gui also from master branch.

**Comment by grzanka** [comment]
@ljelen is it still valid ?
What do you mean by "install pytrip from sources" ?

**Comment by ljelen** [comment]
can not reproduce
