### ISSUE TITLE
Hard to recognize plan from a patient in a tree

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#306]
Now both share the same name (here: inspire):

![image](https://user-images.githubusercontent.com/7374733/83251054-553fa200-a1a9-11ea-8bc5-f09be42cea9f.png)

Such information can be added in tree labels i.e.:
" Patient: inspire" -> "Plan: inspire" -> "Field : 1"

**Comment by ljelen** [comment]
![image](https://user-images.githubusercontent.com/47323191/83336556-c6b84700-a2b4-11ea-9123-92c0d54482fd.png)
