### ISSUE TITLE
Fix welcome screen

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytripgui#35]
wrong software name, disclamer has strange line breaks, last lines are hidden, check if version name is not hardcoded.

**Comment by grzanka** [comment]
Related to #32

**Comment by nbassler** [comment]
indeed. Propose removing the contents from the wxbuilder files, and update the labels at runtime instead, to avoid repetition of the same text.

**Comment by nbassler** [comment]
Closed by #37
