### ISSUE TITLE
Test fails because of qt version

### ISSUE THREAD

**Issue by ljelen** [pytrip/pytripgui#396]
Test fails with this message:
```ERROR: PyQt < 5.11 is not supported by pytest-qt, use 5.11+ instead.```

https://travis-ci.com/github/pytrip/pytripgui/jobs/512159713

**Comment by grzanka** [comment]
@ljelen please check if this is still valid, we have new tests requirements now:
https://github.com/pytrip/pytripgui/blob/master/tests/requirements-test.txt

**Comment by ljelen** [comment]
> @ljelen please check if this is still valid, we have new tests requirements now:
> https://github.com/pytrip/pytripgui/blob/master/tests/requirements-test.txt

it works now :)
