### ISSUE TITLE
Slider does not work properly

### ISSUE THREAD

**Issue by rozchlastywacz** [pytrip/pytripgui#427]
After dragging slider up and down few times it still moves after releasing it, moreover - it somehow tracks back its positions and ends back in initial position, where it was dragged from, check the video out:

https://user-images.githubusercontent.com/44035398/129337163-dd7f98d9-3add-42c3-b2ba-8581b34c7097.mp4

**Comment by michal367** [comment]
it happens after creating a plan and then it is on all canvases

**Comment by grzanka** [comment]
I confirm
