### ISSUE TITLE
VOI list event listeners

### ISSUE THREAD

**Issue by rozchlastywacz** [pytrip/pytripgui#453]
Clicking on element on the does NOT change tha status of checkbox but it emits an event which is responsible for updating whole canvas. 
What do we want to have:
- clicking on element of the VOI list should change status of that element's checkbox and update canvas
or
- clicking on element of the VOI list should NOT change status of that element's checkbox and NOT update canvas

Either way, changes in code should be done. 
In first option, we need to add changing checkbox status after clicking on the list element.
In second, we need to remove updating canvas after clicking on elements list and make it react only for checkbox status change

Here is a video with breakpoints in code that shows what I write about:

https://user-images.githubusercontent.com/44035398/130643333-4fdf97f9-8068-48df-a552-cb79578d3f05.mp4

**Comment by rozchlastywacz** [comment]
@grzanka what do you think?

**Comment by grzanka** [comment]
I'd say that the most intuitive option from user perspective is:
 - clicking on element of the VOI list should change status of that element's checkbox and update canvas
