### ISSUE TITLE
Migration to wxPython Phoenix

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#51]
Windows machine with:

- python 2.7.13 64bit (installed from https://www.python.org/downloads/release/python-2713/, not anaconda or similar)
- numpy + scipy (64bit) installed from gohlke repo via pip (http://www.lfd.uci.edu/~gohlke/pythonlibs/)
- pytrip98 and its deps installed via pip
- wxPython Phoenix 3.0.3.dev2812 installed using command `pip install --upgrade --trusted-host wxpython.org --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix --only-binary="all" -V`
- pytrip98gui source code

Starting pytripgui/main.py file gives following error:
![image](https://cloud.githubusercontent.com/assets/7374733/22855261/9844a54a-f07d-11e6-9396-33b8907527cd.png)

It looks that wxPython Phoenix is different from classical wxPython.

I've found here:
http://stackoverflow.com/questions/37377831/attributeerror-module-object-has-no-attribute-systemsettings-getfont#comment62302346_37390810

useful link:
https://wxpython.org/Phoenix/docs/html/MigrationGuide.html

Maybe we could have the code compatible with both: "classical" and "phoenix" wxPython

**Comment by grzanka** [comment]
More links https://wxpython.org/Phoenix/docs/html/classic_vs_phoenix.html#classic-vs-phoenix

**Comment by grzanka** [comment]
TODO
 - [ ] check which wxPython (classic or phoenix) is installed on Debian when using standard `apt-get` method
 - [ ] find a webpage and installation method of classic wxPython on Windows

**Comment by grzanka** [comment]
According to https://wxpython.org the last release of classic wxPython dates back do 2014
> (28-Nov-2014) wxPython (classic) 3.0.2.0 has been released
Does it mean it is dead ?

It looks that the newest wxPython I found in Debian repos is 3.0.2.0 found in unstable sid:
https://packages.debian.org/source/sid/wxpython3.0

Stable jessie Debian has wxPython 3.0.1.0

Phoenix webpage:
https://wxpython.org/Phoenix/docs/html/index.html
says:

> Phoenix is the code name of a new implementation of wxPython. The name comes from the mythical bird that bursts into flames at the end of its life and from the ashes is reborn as a new, stronger, and better phoenix. Likewise the intent with the wxPython Phoenix project is throw almost everything from wxPython Classic into the fire to be built anew from the ashes of its former self, without all of the old crud that had built up over the long life of Classic.

This looks that we should expect a lot of incompatibilities.

I haven't found any releases of wxPython phoenix :/

**Comment by nbassler** [comment]
(Link to current packages in debian)
https://tracker.debian.org/pkg/wxpython3.0

**Comment by grzanka** [comment]
Anaconda can install wxpython classic 3.0.0.0: https://anaconda.org/anaconda/wxpython for Windows/Linux/Mac

**Comment by grzanka** [comment]
I propose to stick with wxpython classic, despite the fact it looks like a dead project (last commit 2014). It is present in the stable/testing/unstable Debian and in all Ubuntu repos. It means it won't disappear from market for next few years.

wxpython has just one drawback: installation via pip is not possible. Linux users needs to have root access to install it via apt-get. Haven't tested it much under Windows, but it looks that the best support is from Anaconda (https://www.continuum.io/downloads) which is simplifying also other issues, like scipy installation.

wxpython Phoenix is alive and developed, but was never officially release and user installation via pip is problematic.

@nbassler what do you think ?

**Comment by nbassler** [comment]
switch to PyQT.

**Comment by grzanka** [comment]
Switching to Qt is a big task, but can be considered if we get any manpower.
There is also an alternative called PySide:
http://wiki.qt.io/Differences_Between_PySide_and_PyQt

**Comment by nbassler** [comment]
PyQt5 will resolve this.
