### ISSUE TITLE
Converting to TRiP format and back to DICOM - problem with contours

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#58]
Linux, pytripgui 1.2.2 + pytrip 1.3.1

I took DICOM files from https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/xio-4.33.02-phantom-chest/
and converted them to TRiP98 format (hed+ctx+vdx).

Converted data in TRiP98 loads correctly (upper right image), contrours looks OK.

After converting back from TRiP98 to DICOM, contours gets spoiled (lower left image).

![screenshot_2017-02-13_18-38-57](https://cloud.githubusercontent.com/assets/7374733/22901759/a4c1dc26-f22a-11e6-8884-26f0996bdb0c.png)

**Comment by nbassler** [comment]
could this be a PyTRiP issue, rather than a PyTRiPGUI issue?

**Comment by grzanka** [comment]
I think so

**Comment by asg16** [comment]
The problem is the conversion from voxelplan format to DICOM, this is an issue we discussed already I think. So far, all DICOM RTStructures that I have produced with different versions of pytrip, can be loaded in Eclipse but the structures show some scaling error, shape is correct but the are too big and fall to the right lower corner, meaning..... maybe the pixel size was not taken into account? 0.9375, a bit smaller than 1, in the test files I used, could produce this effect.
I attach a picture produced with another voxelplan viewer, not pytrip. The last version I tested is 1.3.1.
![dose_056](https://cloud.githubusercontent.com/assets/23524371/22966722/c564f352-f363-11e6-8e62-4e70e8ec4299.PNG)

**Comment by nbassler** [comment]
@asg16 that particular file, does it view correctly in PyTRiPGUI, but incorrectly in the alternative viewer, or is it wrong in both?

**Comment by asg16** [comment]
I cannot install the GUI in my laptop right now, but we checked some time ago on a different laptop, with an older version of the pytrip GUI and the display of the contours showed the same error. And Eclipse shows the same error, which is actually what matters to me the most. It is not a display error, it is an error of the dicom contours.

**Comment by grzanka** [comment]
I think we should also investigate axis orientation as from the first picture I've sent the problem is not only related to scaling

**Comment by asg16** [comment]
I did a check with a simple square contour, and now I can confirm, the problem is the voxel size is not taken properly into account, therefore each coordinate is scaled like this: (x/0.9375, y/0.9375).
And also the slice number of each contour is increased in 1: contour on slice 50 is drawn on slice 51 on the dicom file and so on

**Comment by nbassler** [comment]
@as16, the pixel spacing issue is a PyTRiP issue.

It seems to be a different issue than what @grzanka  first reported. The pixel size issue is moved to https://github.com/pytrip/pytrip/issues/245 (please use that thread for further discussions)

**Comment by nbassler** [comment]
this seems more tricky, somehow the contour assignment per slice is broken

**Comment by grzanka** [comment]
I have some hints.
When loading DICOM data (generating .vdx) following code is used:
https://github.com/pytrip/pytrip/blob/v1.3.1/pytrip/vdx.py#L988

```
        self.contour.append(
            Contour(pytrip.res.point.array_to_point_array(np.array(dcm.ContourData, dtype=float), offset)))
```

which leads to: https://github.com/pytrip/pytrip/blob/v1.3.1/pytrip/res/point.py#L96
```
def array_to_point_array(points, offset):
    point = [[points[3 * i] - offset[0], points[3 * i + 1] - offset[1], points[3 * i + 2] - offset[2]]
             for i in range(int(len(points) / 3))]
    return point
```

For example DICOM contour from https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/xio-4.33.02-phantom-chest/SS.rtp1.12.20080627A.5.dcm

has offset `[-179.9936, -179.9936, -167.8]`

First contour read from DICOM starts with point (15.8,-93.5,-167.8)
```
# grzanka at nz61-6 in ~/PycharmProjects/pytrip on git:master ✖︎ [22:04:46]
→ dcmdump /home/grzanka/PycharmProjects/data/xio-4.33.02-phantom-chest/SS.rtp1.12.20080627A.5.dcm | grep ContourData | head -n 1                                     ~/PycharmProjects/pytrip
        (3006,0050) DS [15.8\-93.5\-167.8\20.0\-93.5\-167.8\20.7\-92.8\-167.8\25.0\-92.8\-... # 8236,1326 ContourData
```

Writing it to .vdx file we get:
```
 195.794 86.494 0.000 0.000 0.000 0.000
```

Which seems correct, as:
```
195.794 = 15.8 - (-179.9936)
86.494 = -93.5 - (-179.9936)
0.0 = -167.8 - (-167.8)
```

Rest of the story will come soon

**Comment by grzanka** [comment]
@asg16 I confirm that no scaling with pixel size is applied when generating .vdx files in 2.0 format.

**Comment by nbassler** [comment]
@grzanka pls discuss pixel_scaling issues in https://github.com/pytrip/pytrip/issues/245

**Comment by nbassler** [comment]
regarding the offset: it seems to be more than just a missing offset, since the contours are not systematically shifted with a constant. The case you showed  there were only to contours from two slices which were mapped to all other slices.

**Comment by grzanka** [comment]
I am afraid that there migh be several other factors included:
 - mapping between contours and CT slices via UIDs
 - sorting slices via filename or via slice position
 - general bugs in writing/reading vdx (somewhere I seen different number of points in contours for vdx and for dicom)

**Comment by nbassler** [comment]
I think it is related to bad mapping, i see weird issue in vdx.py when converting to dicom.

Contours are e.g. 2.5 mm in thick slices, but somehow get_position() suddenly increses by 0.1 for no obvious reason. Looks like a rounding error. Comparison fails, and then ROI is mapped to a default "1.2.3" UID, guess that is what RayStation doesnt like (fair enough)

The weird thing is that the base VDX file seems ok, the contours are in proper slices and increase in 2.5 mm steps as they should.

**Comment by nbassler** [comment]
Correction: in fact the VDX file seems to be broken already:

slice 0
slice_in_frame 0.000
 195.794 86.494 0.000 0.000 0.000 0.000
(...)
slice 1
slice_in_frame 2.500
 195.794 86.494 2.500 0.000 0.000 0.000
(...)
slice 118
slice_in_frame 295.100
 178.494 260.594 295.100 0.000 0.000 0.000
(...)
slice 119
slice_in_frame 297.600
 174.094 254.494 297.600 0.000 0.000 0.000


this leads to bad mapping, when vdx.py tries to map a contour at 297.600 to 297.500... it does not find that slice, so nothing is mapped. 

In fact I think this may related to the other bug you had https://github.com/pytrip/pytripgui/issues/58

**Comment by nbassler** [comment]
printing the dicom contour data upon conversion from dicom->vdx:  in add_dicom_contour():

```
[173.49359999999999, 263.59359999999998, 165.0]
[179.19359999999998, 270.49360000000001, 167.5]
[178.99359999999999, 270.39359999999999, 170.10000000000002]
[178.89359999999999, 270.39359999999999, 172.60000000000002]
[178.7936, 270.29359999999997, 175.10000000000002]
[178.69359999999998, 270.29359999999997, 177.60000000000002]
[174.09359999999998, 264.1936, 180.10000000000002]
```

**Comment by nbassler** [comment]
The issue can be traced back to the dicom file:
```
NB: offset[2] -167.8
[ 15.2 -79.5  -0.3 ...,  15.2 -79.5  -0.3]      <-- DICOM contour data
[195.19359999999998, 100.49359999999999, 167.5]
NB: offset[2] -167.8
[ 15.8 -80.1   2.3 ...,  15.8 -80.1   2.3]       <--- DICOM contour data
```
the dicom file just took a step of 2.6 mm here.

**Comment by nbassler** [comment]
```
gdcmdump /local/dicom/xio-4.33.02-phantom-chest/SS.rtp1.12.20080627A.5.dcm | grep -i "contour data" 

(...)

        (3006,0050) ?? (DS) [15.2\-79.5\-0.3\19.4\-79.5\-0.3\20.1\-78.8\-0.3\25.0\-78.8\-0.3\25.7\-78.1\-0.3\30.7\-78.1\-0.3\31.4\-77.4\-0.3\36.3\-77.4\-0.3\37.0\-76.7\-0.3\42.6\-76.7\-0.3\43.3\-76.0\-0.3\48.2\-76.0\-0.3\48.9\-75.3\-0.3\53.9\-75.3\-0.3\54.6\-74.6\-0.3\57.4\-74.6\-0.3\]         # 8126,3-3n Contour Data
        (3006,0050) ?? (DS) [15.8\-80.1\2.3\16.5\-79.4\2.3\22.1\-79.4\2.3\22.8\-78.7\2.3\27.1\-78.7\2.3\27.8\-78.0\2.3\32.0\-78.0\2.3\32.7\-77.3\2.3\37.6\-77.3\2.3\38.3\-76.6\2.3\43.2\-76.6\2.3\43.9\-75.9\2.3\48.9\-75.9\2.3\49.6\-75.2\2.3\53.8\-75.2\2.3\54.5\-74.5\2.3\57.3\-74.5\2.3\5]         # 7460,3-3n Contour Data
```

**Comment by nbassler** [comment]
Suspect the bad slice mapping was not related to the contour issue from the first post in this thread.

**Comment by nbassler** [comment]
Persists in 1.3.2 and 0.2.5
