### ISSUE TITLE
Loading Pinaccle DICOM , structure with no name

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#60]
After loading some Pinaccle DICOM from https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/pinnacle3-8.2g-phantom-chest/
:

Structures do not get any reasonable name

![image](https://cloud.githubusercontent.com/assets/7374733/22901892/212a6738-f22b-11e6-9da5-6afc68b737ea.png)

**Comment by nbassler** [comment]
Here for the Pinnacle RT version, compared to RayStation (from @okejdokej )

![pytrip_rois](https://cloud.githubusercontent.com/assets/7140398/22935531/242d1af4-f2d3-11e6-942a-10f3967ac729.png)

![phantom_imrt_rois_name](https://cloud.githubusercontent.com/assets/7140398/22935557/359c390a-f2d3-11e6-84ad-0b318790a150.png)

![phantom_imrt_pois_name](https://cloud.githubusercontent.com/assets/7140398/22935564/3957f26e-f2d3-11e6-82ad-8b19735213d6.png)


Note also POIs are treated as ROIs in the tree, however they are not displayed either.

**Comment by nbassler** [comment]
This is an issue in PyTRiP, I will fix it.
Closing it here.
