### ISSUE TITLE
Pytripgui freezing on Windows

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#66]
I was trying to open some DICOM files on Windows using pytripgui.
After loading DICOM file from aria-phantom-contours-branching 
the app freezed.

After quick and blind debugging I realized that commenting out:
```
        # self.toolbar.ClearTools()
```
https://github.com/pytrip/pytripgui/blob/v0.2.2/pytripgui/main.py#L274
in bind_default_toolbar method of MainFrame class in pytripgui/main.py solves the problem.

I didn't have time to invesigate role of `self.toolbar.ClearTools()` method

**Comment by nbassler** [comment]
will work in Qt5 version.
