### ISSUE TITLE
switching to Sagittal plane doesn't work

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytripgui#81]
PyTRiPGUI 0.2.6-dev (current master)
and button is spelled wrong (sagital -> sagittal)

**Comment by nbassler** [comment]
Traceback (most recent call last):
  File "/home/bassler/Projects/pytripgui/pytripgui/panels/plotpanel.py", line 200, in plot_mode_changed
    self.Draw()
  File "/home/bassler/Projects/pytripgui/pytripgui/panels/plotpanel.py", line 659, in Draw
    self.plotutil.plot(self.image_idx)
  File "/home/bassler/Projects/pytripgui/pytripgui/guiutil.py", line 342, in plot
    self.plot_text(idx)
  File "/home/bassler/Projects/pytripgui/pytripgui/guiutil.py", line 529, in plot_text
    "Slice Position: {:.1f} mm ".format(self.ctx.slice_pos[idx]),
IndexError: list index out of range

**Comment by grzanka** [comment]
Related to https://github.com/pytrip/pytripgui/pull/75/files ?

**Comment by nbassler** [comment]
I think it was broken long before. Needs some rework anyway, I will be happy to go through it when it becomes more important.

**Comment by grzanka** [comment]
After loading DICOM it works well with GUI 0.2.5 and pytrip 1.3.1 (in my case)

**Comment by grzanka** [comment]
![image](https://cloud.githubusercontent.com/assets/7374733/23463538/ccea6efa-fe89-11e6-9e32-c724374c3d98.png)
![image](https://cloud.githubusercontent.com/assets/7374733/23463546/d4171214-fe89-11e6-821b-03da1c8f0784.png)

**Comment by nbassler** [comment]
enable stuctures maybe?

I have it working with a simple fix

**Comment by grzanka** [comment]
Still works 
![image](https://cloud.githubusercontent.com/assets/7374733/23463648/38547500-fe8a-11e6-9833-3e587d0aa9a0.png)

**Comment by grzanka** [comment]
The last commit when it was working is db7f226 so the problem was introduced either in PR #75 or #78
