### ISSUE TITLE
Cannot execute TRiP

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytripgui#99]
PyTRiP 1.5.0
PyTRiPGUI 0.3.0

- Load a CTX + VDX (TST000)
- Create New Plan
- Select target CTV
- execute TRiP
![screenshot_2017-03-26_19-35-35](https://cloud.githubusercontent.com/assets/7140398/24333621/a46f5338-125b-11e7-8211-d407346231b4.png)

**Comment by grzanka** [comment]
which version of python-wxwigets ?

**Comment by nbassler** [comment]
Debian testing default 3.0.2.0+dfsg-3
